### ISSUE TITLE
file names are confusing

### ISSUE THREAD

**Issue by fdiblen** [nlesc-dirac/sagecal#10]
sometimes files are called like _clmfit_nocuda.c_ 
and some times like _predict_withbeam_gpu.c_

that should be consistent

**Comment by HannoSpreeuw** [comment]
As Faruk noticed, clmfit_nocuda.c and robust_lbfgs_nocuda.c are strangely used by Makefile.gpu.

**Comment by fdiblen** [comment]
@HannoSpreeuw 
@SarodYatawatta 
is this still the case?
Maybe we can rename these files already.

**Comment by SarodYatawatta** [comment]
some files need more refactoring, so they will be renamed at a later stage

**Comment by fdiblen** [comment]
@SarodYatawatta @HannoSpreeuw 
any updates on this issue?
we should fix this before the next release

**Comment by SarodYatawatta** [comment]
No update yet. Only after October.

**Comment by fdiblen** [comment]
This issue makes GPU support complicated. 
Suggestions:
- filenames that are not related to the GPU implementation should **never** include 'cuda' keyword. For example: robust_lbfgs_nocuda.c
- if the file will be compiled with gpu support, it should **always** include '_cuda' at the end. Example:
rtr_solve_robust_cuda.c
- Some files has '_cuda' and they should be renamed for consistency. 
    - rtr_solve_robust_cuda_admm.c --> rtr_solve_robust_admm_cuda.c

**Comment by fdiblen** [comment]
related to #42
