### ISSUE TITLE
code analysis is needed

### ISSUE THREAD

**Issue by fdiblen** [nlesc-dirac/sagecal#11]
it is strange to have the following line in lib/Dirac/Dirac.h
#ifndef SAGECAL_H
#define SAGECAL_H

A code analysis is needed. A simplest analysis can be performed using
http://cppcheck.sourceforge.net/

**Comment by fdiblen** [comment]
@HannoSpreeuw Do we have code analysis now?

**Comment by HannoSpreeuw** [comment]
We performed code analysis using some clang tool during the last sprint at ASTRON.
