### ISSUE TITLE
Latitude and longitude of the phase center in the lunar frame

### ISSUE THREAD

**Issue by SoniaGhosh24** [nlesc-dirac/sagecal#207]
Hi,

I am using `uvwriter.cpp` script. It would be very helpful to print the derived longitude and latitude of the phase center on the lunar surface (`s_lon` and `s_lat`) as returned from the following function in this script.

`reclat_c(srcrect, &s_radius, &s_lon, &s_lat);`

Thanks in advance!

**Comment by SarodYatawatta** [comment]
Fixed

**Comment by SarodYatawatta** [comment]
Use -z option, will overwrite the phase center of the MS with the one in zenith direction at station 0
