### ISSUE TITLE
Potential Redundant Conversion of RA/DEC to Radians in uvwriter.cpp 

### ISSUE THREAD

**Issue by SoniaGhosh24** [nlesc-dirac/sagecal#209]
Hello,

I am using `uvwriter.cpp` script. While trying to understand the script, I came across the following part where the phase center coordinates (Right Ascension (RA) and Declination (DEC)) are read from the MS:
```
MSField _field = Table(ms.field());
ArrayColumn<double> ref_dir(_field, MSField::columnName(MSFieldEnums::PHASE_DIR));
Array<double> dir = ref_dir(0);
double *ph = dir.data();
double ra0 = ph[0];
double dec0 = ph[1];
```
My understanding is that in the MS, the RA and DEC is stored in radians. Now, in the later part of the script, I see a snippet where the RA and DEC are being converted to rectangular coordinates. But they are also multiplied by  `rpd_c()` which if I understand correctly is a function in CSPICE package that converts angles from degrees to radians.
`
radrec_c(1.0, ra0 * rpd_c(), dec0 * rpd_c(), v2000);`

I assume the `radrec_c` function expects its angular inputs (RA and Dec) to be in radians, so if they are already in the correct unit, we can directly pass them to the function without any conversion.

Could you kindly look into this and make the necessary changes?
Thanks in advance!

**Comment by SarodYatawatta** [comment]
Fixed
