### ISSUE TITLE
Fix memory leaks detected by cppcheck.

### ISSUE THREAD

**Issue by HannoSpreeuw** [nlesc-dirac/sagecal#22]
Lots of memory leaks detected by cppcheck, but also other issues.
See attached cppcheck output .
[cppcheck.txt](https://github.com/nlesc-dirac/sagecal/files/1759314/cppcheck.txt)

**Comment by HannoSpreeuw** [comment]
I also tried the clang tools scan-build and scan-view.
These give a somewhat fancier layout of the bugs.
scan-build make
or
scan-build make -f Makefile.gpu

next 
scan-view /tmp/somedirectory

However the scan-view output is displayed in a browser on a local IP address http://127.0.0.1:8181/
and I do not seem to be able to figure out how this should be exported to a file.

**Comment by SarodYatawatta** [comment]
fixed everything but one warning, I checked the warning, it is okay
