### ISSUE TITLE
cmake build fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by HannoSpreeuw** [nlesc-dirac/sagecal#30]
cmake .. -DENABLE_CUDA=OFF
make
---->
![image](https://user-images.githubusercontent.com/11661087/36740443-b69c865c-1be2-11e8-841a-ba9281f588c7.png)

**Comment by fdiblen** [comment]
fixed by 2a4a93f953bf0047ed5564367e0089942a1b24f2
