### ISSUE TITLE
clang tools scan-build and scan-view detect multiple issues in building libdirac.a for GPU

### ISSUE THREAD

**Issue by HannoSpreeuw** [nlesc-dirac/sagecal#31]
so this is from _scan-view_ on the output of 
_scan-build make -f Makefile.gpu_
in Dirac

![image](https://user-images.githubusercontent.com/11661087/36742327-addc2cc0-1be7-11e8-8d4d-c5dfbd606fb1.png)

Excluding the dead assignments:

Unix API | Allocator sizeof operand mismatch | lbfgs.c | 228 | 1
Logic error | Assigned value is garbage or undefined | lmfit.c | 457 | 26 |  
Logic error | Assigned value is garbage or undefined | lmfit.c | 773 | 23
Logic error | Assigned value is garbage or undefined | lmfit.c | 1324 | 23
Logic error | Dereference of null pointer | lmfit.c | 1838 
Logic error | Dereference of null pointer | admm_solve.c | 915 | 24 
Memory Error | Memory leak | lmfit.c | 951 | 33 
Logic error | Result of operation is garbage or undefined | lmfit.c | 857 | 25 
Logic error | Result of operation is garbage or undefined | lmfit.c | 931 | 27 
Logic error | Result of operation is garbage or undefined | lmfit.c | 1958 | 30 
Logic error | Result of operation is garbage or undefined | lmfit.c | 2080 | 31 
Logic error | Result of operation is garbage or undefined | admm_solve.c | 1000 | 24 
Logic error | Result of operation is garbage or undefined | admm_solve.c | 1084 | 25 
Logic error | Result of operation is garbage or undefined | admm_solve.c | 1402 | 22 |
Unix API | Undefined allocation of 0 bytes (CERT MEM04-C; CWE-131) | robust_lbfgs_nocuda.c | 162 | 16 
Logic error | Uninitialized argument value | clmfit.c | 1011 | 23 
Logic error | Uninitialized argument value | robustlm.c | 476 | 26 
Logic error | Uninitialized argument value | oslmfit.c | 521 | 36

**Comment by SarodYatawatta** [comment]
Fixed
