### ISSUE TITLE
clang tools scan-build and scan-view detect multiple issues in building libradio.a for GPU

### ISSUE THREAD

**Issue by HannoSpreeuw** [nlesc-dirac/sagecal#32]
so this is from scan-view on the output of
scan-build make -f Makefile.gpu
in Radio
![image](https://user-images.githubusercontent.com/11661087/36742867-1311d576-1be9-11e8-8d09-ab4446962009.png)

Excluding the dead assignments:

Unix API | Allocator sizeof operand mismatch | predict_withbeam_gpu.c | 236 | 1 
Unix API | Allocator sizeof operand mismatch | predict_withbeam_gpu.c | 240 | 1 
Unix API | Allocator sizeof operand mismatch | predict_withbeam_gpu.c | 244 | 1 
Unix API | Allocator sizeof operand mismatch | predict_withbeam_gpu.c | 850 | 1 
Unix API | Allocator sizeof operand mismatch | predict_withbeam_gpu.c | 854 | 1 
Unix API | Allocator sizeof operand mismatch | predict_withbeam_gpu.c | 858 | 1 
Unix API | Allocator sizeof operand mismatch | predict_withbeam_gpu.c | 1409 | 1 
Unix API | Allocator sizeof operand mismatch | predict_withbeam_gpu.c | 1413 | 1 
Unix API | Allocator sizeof operand mismatch | predict_withbeam_gpu.c | 1417 | 1
Logic error | Result of operation is garbage or undefined | readsky.c | 704 | 12 
Logic error | Uninitialized argument value | predict_withbeam_gpu.c | 445 | 12 
Logic error | Uninitialized argument value | predict_withbeam_gpu.c | 1061 | 12 
Logic error | Uninitialized argument value | predict_withbeam_gpu.c | 1630 | 19

**Comment by SarodYatawatta** [comment]
Fixed
