### ISSUE TITLE
cmake build fails on Cent OS 7.4 on fs5 on DAS5

### ISSUE THREAD

**Issue by HannoSpreeuw** [nlesc-dirac/sagecal#37]
[hspreeuw@fs5 build]$ cmake .. -DCASACORE_INCLUDE_DIR=/cm/shared/package/casacore/v2.3.0-gcc-4.9.3/include/ -DWCSLIB_INCLUDE_DIR=/cm/shared/package/wcslib/5.16-gcc-4.9.3/include -DWCSLIB_LIBRARY=/cm/shared/package/wcslib/5.16-gcc-4.9.3/lib/libwcs.so -DCFITSIO_LIBRARY=/cm/shared/package/cfitsio/3410-gcc-4.9.3/lib/libcfitsio.so -DCFITSIO_INCLUDE_DIR=/cm/shared/package/cfitsio/3380-gcc-4.9.3/include/ -DHDF5_LIBRARY_DIRS=/cm/shared/package/hdf5/1.8.17/lib
......
make -j4
......
/home/hspreeuw/sagecal-code/src/MS/main.cpp:471:135: warning: ISO C++98 does not support the ‘%lf’ gnu_printf format [-Wformat=]
/home/hspreeuw/sagecal-code/src/MS/main.cpp:471:135: warning: ISO C++98 does not support the ‘%lf’ gnu_printf format [-Wformat=]
[100%] Linking CXX executable ../../dist/bin/sagecal
/cm/shared/package/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
make[2]: *** [dist/bin/sagecal] Error 1
make[1]: *** [src/MS/CMakeFiles/sagecal.dir/all] Error 2
make: *** [all] Error 2

**Comment by HannoSpreeuw** [comment]
This is on fs5 on DAS5. 
gcc 4.9.3, casacore 2.3.0 cmake 3.8.2

this command
cmake -DCFITSIO_ROOT_DIR=/cm/shared/package/cfitsio/3380-gcc-4.9.3 -DCASACORE_ROOT_DIR=/cm/shared/package/casacore/v2.3.0-gcc-4.9.3 -DWCSLIB_INCLUDE_DIR=/cm/shared/package/wcslib/5.13-gcc-4.9.3/include -DWCSLIB_LIBRARY=/cm/shared/package/wcslib/5.13-gcc-4.9.3/lib/libwcs.so -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_LINKER=/cm/shared/package/gcc/4.9.3/bin/gcc -DCMAKE_CXX_FLAGS=-L/cm/shared/package/cfitsio/3380-gcc-4.9.3/lib -DCMAKE_C_FLAGS=-L/cm/shared/package/cfitsio/3380-gcc-4.9.3/lib ..
worked yesterday, but not today, giving "cannot find -lcfitsio" error.
Although it produced a sagecal executable, this executable was incorrect.

What we did is alter the command that cmake issues, from build/src/MS:
/cm/shared/package/gcc/4.9.3/bin/g++  -std=c++11 -g -O3 -Wall -Wextra -W -pedantic -ansi -fPIC -fpermissive   CMakeFiles/sagecal.dir/data.cpp.o CMakeFiles/sagecal.dir/main.cpp.o  -o ../../dist/bin/sagecal  -L/home/hspreeuw/sagecal-code/build/dist/lib  -L/home/hspreeuw/sagecal-code/src/MS/../lib/Dirac  -L/home/hspreeuw/sagecal-code/src/MS/../lib/Radio -Wl,-rpath,/home/hspreeuw/sagecal-code/build/dist/lib:/home/hspreeuw/sagecal-code/src/MS/../lib/Dirac:/home/hspreeuw/sagecal-code/src/MS/../lib/Radio:/cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib:/cm/shared/package/wcslib/5.13-gcc-4.9.3/lib:/cm/shared/package/cfitsio/3380-gcc-4.9.3/lib: /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_coordinates.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_images.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_msfits.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_lattices.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_mirlib.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_fits.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_ms.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_measures.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_scimath.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_tables.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_scimath_f.so /usr/lib64/libopenblas.so /usr/lib64/libopenblas.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_casa.so /usr/lib64/libm.so -ldl /usr/lib64/libopenblas.so /usr/lib64/libopenblas.so /usr/lib64/libopenblas.so /cm/shared/package/wcslib/5.13-gcc-4.9.3/lib/libwcs.so /usr/lib64/libm.so -lglib-2.0 -lopenblas -lgfortran -lpthread -lcfitsio -lm -ldirac -lradio /cm/shared/package/cfitsio/3380-gcc-4.9.3/lib/libcfitsio.so /usr/lib64/libm.so /usr/lib64/libopenblas.so /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_casa.so -ldl /cm/shared/package/wcslib/5.13-gcc-4.9.3/lib/libwcs.so -lglib-2.0 -lopenblas -lgfortran -lpthread -lcfitsio -lm -ldirac -lradio /cm/shared/package/cfitsio/3380-gcc-4.9.3/lib/libcfitsio.so
to 
......
-L/cm/shared/package/cfitsio/3380-gcc-4.9.3/lib/
so everything the same except the last argument where we added -L and removed libcfitsio.so.

Now it works and produces a correct executable. 
But we cannot issue this from cmake, which is frustrating.

[hspreeuw@fs5 test]$ echo $PATH
/home/hspreeuw/anaconda3/bin:/cm/shared/apps/torque/6.1.1/bin:/cm/shared/apps/torque/6.1.1/sbin:/cm/shared/package/cmake/3.8.2/bin:/cm/shared/package/casacore/v2.3.0-gcc-4.9.3/bin:/cm/shared/package/wcslib/5.16-gcc-4.9.3/bin:/cm/shared/package/gcc/4.9.3/bin:/cm/shared/package/hdf5/1.8.17/bin:/home/hspreeuw/anaconda3/bin:/cm/shared/apps/slurm/17.02.2/sbin:/cm/shared/apps/slurm/17.02.2/bin:/cm/shared/apps/torque/6.1.1/bin:/cm/shared/apps/torque/6.1.1/sbin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/usr/java/latest//bin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/3.2.10/bin:/cm/shared/package/reserve.slurm/bin:/home/hspreeuw/.local/bin:/home/hspreeuw/bin:/usr/java/latest//bin:/home/hspreeuw/.local/bin:/home/hspreeuw/bin

[hspreeuw@fs5 test]$ echo $LD_LIBRARY_PATH                                                                                                                                   
/cm/shared/package/cfitsio/3380-gcc-4.9.3/lib:/cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib:/cm/shared/package/wcslib/5.16-gcc-4.9.3/lib:/cm/shared/package/fftw/3.3.4-gcc-4.9.3/lib:/cm/shared/package/lapack/3.8.0-gcc-4.9.3/lib64:/cm/shared/package/openblas/0.2.17mt/lib:/cm/shared/package/boost/boost-1.60.0/lib:/cm/shared/package/gcc/4.9.3/lib:/cm/shared/package/gcc/4.9.3/lib64:/cm/shared/package/cfitsio/3410-gcc-4.9.3/lib:/cm/shared/package/hdf5/1.8.17/lib:/cm/shared/apps/slurm/17.02.2/lib64/slurm:/cm/shared/apps/slurm/17.02.2/lib64

**Comment by SarodYatawatta** [comment]
Also add output of 
ldd /cm/shared/package/cfitsio/3380-gcc-4.9.3/lib/libcfitsio.so

**Comment by HannoSpreeuw** [comment]
[hspreeuw@node505 Scripts]$ ldd /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_casa.so
/cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_casa.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_casa.so)
/cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_casa.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /cm/shared/package/casacore/v2.3.0-gcc-4.9.3/lib/libcasa_casa.so)
       linux-vdso.so.1 =>  (0x00002aaaaaaab000)
       libreadline.so.6 => /lib64/libreadline.so.6 (0x00002aaaab0cf000)
       libncurses.so.5 => /lib64/libncurses.so.5 (0x00002aaaab316000)
       libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00002aaaab53d000)
       libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaab767000)
       libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00002aaaab96c000)
       libm.so.6 => /lib64/libm.so.6 (0x00002aaaabc74000)
       libgomp.so.1 => /lib64/libgomp.so.1 (0x00002aaaabf76000)
       libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002aaaac19d000)
       libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaac3b3000)
       libc.so.6 => /lib64/libc.so.6 (0x00002aaaac5cf000)
       /lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
[hspreeuw@node505 Scripts]$ ldd /cm/shared/package/wcslib/5.16-gcc-4.9.3/lib/libwcs.so
       linux-vdso.so.1 =>  (0x00002aaaaaaab000)
       libm.so.6 => /lib64/libm.so.6 (0x00002aaaaae20000)
       libc.so.6 => /lib64/libc.so.6 (0x00002aaaab123000)
       /lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
[hspreeuw@node505 Scripts]$ ldd /cm/shared/package/cfitsio/3380-gcc-4.9.3/lib/libcfitsio.so
       linux-vdso.so.1 =>  (0x00002aaaaaaab000)
       libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaaaee5000)
       libm.so.6 => /lib64/libm.so.6 (0x00002aaaab102000)
       libc.so.6 => /lib64/libc.so.6 (0x00002aaaab404000)
       /lib64/ld-linux-x86-64.so.2 (0x0000555555554000)

**Comment by fdiblen** [comment]
The issue should be fixed now.

Please load the modules below before compiling SageCal.
module load cmake/3.8.2
module load mpich/ge/gcc/64/3.2
module load gcc/4.9.3
module load casacore/2.3.0-gcc-4.9.3
module load wcslib/5.13-gcc-4.9.3
module load wcslib/5.16-gcc-4.9.3
module load cfitsio/3.410-gcc-4.9.3


checkout the **dev** branch and compile it with the instructions below(in source folder):
mkdir build && cd build
cmake  .. -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH
make
make install

$INSTALL_PATH is where you want to install SageCal.

Closing the issue.
Please re-open the issue if you have problems.
