### ISSUE TITLE
add a debug build option which shows all the warnings

### ISSUE THREAD

**Issue by fdiblen** [nlesc-dirac/sagecal#39]

**Comment by HannoSpreeuw** [comment]
I don't understand this.
Presently, we have 
CFLAGS= -Wall -g
so that includes both debugging information as well as all warnings.

Perhaps you mean a separate option 
make debug
as described e.g. [here](https://stackoverflow.com/questions/25797287/how-do-i-add-a-debug-option-to-makefile)?

**Comment by HannoSpreeuw** [comment]
Perhaps @fdiblen can explain what this issue is about.

**Comment by fdiblen** [comment]
It is only used for development purposes.
See:
https://gitlab.kitware.com/cmake/community/wikis/FAQ#how-can-i-build-multiple-modes-without-switching-

**Comment by fdiblen** [comment]
fixed by #65
