### ISSUE TITLE
Test directory is too big

### ISSUE THREAD

**Issue by fdiblen** [nlesc-dirac/sagecal#78]
The code itself is ~3mb but the size of the files in test directory are about 55 mb. Maybe we can store test and example data in a separate repository.

**Comment by HannoSpreeuw** [comment]
We could make sm.ms.tar available through a Surfdrive link.

**Comment by fdiblen** [comment]
We should have a separate repo for data. Also need to refer to the repo in documentation, make changes in the code so that it can fetch the data from that repository.

**Comment by fdiblen** [comment]
As it is only a test data and it is not so big, that should be OK.

**Comment by HannoSpreeuw** [comment]
Do you mean a separate GH repo?

**Comment by HannoSpreeuw** [comment]
I added sm.ms.tar to the new repo
https://github.com/nlesc-dirac/data
So sm.ms.tar may be removed from all SAGECal branches.

However, GH recommends
https://git-lfs.github.com/
for files larger than 50 MB.

**Comment by fdiblen** [comment]
> I added sm.ms.tar to the new repo
> https://github.com/nlesc-dirac/data
> So sm.ms.tar may be removed from all SAGECal branches.
> 
> However, GH recommends
> https://git-lfs.github.com/
> for files larger than 50 MB.

Can you remove the data file from the repo and modify the code/scripts which are using this data?

LFS is not needed. It will just make things more complicated.
