### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by fdiblen** [nlesc-dirac/sagecal#79]
documentation needs to be more structured and clean
For example:
move info to relevant sections
create separate markdown files if necessary
...

**Comment by SarodYatawatta** [comment]
Can we use something better than markdown format? I mean for the tutorial etc.

**Comment by fdiblen** [comment]
Markdown is a 'standard' format and there are many tools to render it. It is also easy to edit.
Any other suggestions than Markdown?

**Comment by fdiblen** [comment]
For tutorial we can use Gitbook.
https://www.gitbook.com

This is also what we use for NLeSC guide.
https://guide.esciencecenter.nl/
