### ISSUE TITLE
coding standard is needed 

### ISSUE THREAD

**Issue by fdiblen** [nlesc-dirac/sagecal#8]
coding standard or at least editorconfig should be added

**Comment by HannoSpreeuw** [comment]
Okay, should not be so difficult. 
How about the [default editorconfig](https://github.com/RReverser/github-editorconfig/blob/master/src/common/res/default.editorconfig)?

**Comment by SarodYatawatta** [comment]
I have no preferences

**Comment by fdiblen** [comment]
solved by #60
