### ISSUE TITLE
Build problem in gpu_support branch:  "_GLIBCXX_MATH_H" is not defined

### ISSUE THREAD

**Issue by HannoSpreeuw** [nlesc-dirac/sagecal#84]
**Describe the bug**
From the build directory in the gpu_support branch:
`make` 
gives
`                 from <command-line>:0:
/cm/shared/package/cuda91/toolkit/9.1.85/include/crt/math_functions.h:8891:5: error: "_GLIBCXX_MATH_H" is not defined [-Werror=undef]
 #if _GLIBCXX_MATH_H && __cplusplus >= 201103L
     ^`

**To Reproduce**
1. `cd build`
2. `module load cuda91` 
3. `module load cmake/3.8.2`
4. `module load casacore/2.3.0-gcc-4.9.3`
5. `cmake .. -DCMAKE_INSTALL_PREFIX=/home/hspreeuw/sagecal-code/src/MS   
-DHAVE_CUDA=TRUE`
5. `make`

**Expected behavior**
A complete build

**Comment by SarodYatawatta** [comment]
what if -D_GLIBCXX_MATH_H is added to the cmake command?

**Comment by HannoSpreeuw** [comment]
Adding 
` -D_GLIBCXX_MATH_H=TRUE` 
does not make a difference.

**Comment by HannoSpreeuw** [comment]
Looking at this [SO post](https://stackoverflow.com/questions/48651574/nvcc-fails-with-the-error-glibcxx-math-h-is-not-defined/48651575#48651575) it does not seem to be anything major.

**Comment by HannoSpreeuw** [comment]
Fixed by
`rm -rf *` in ```build``` directory before anything else.
There must have been some remainder from previous build attempts still floating around.
