### ISSUE TITLE
run Sagecal in GPU supported containers

### ISSUE THREAD

**Issue by fdiblen** [nlesc-dirac/sagecal#94]
Run Sagecal with GPU support in a container.

For Docker nvidia-docker would be a good starting point.
https://github.com/NVIDIA/nvidia-docker

For Singularity this may help:
https://singularity.lbl.gov/faq#does-singularity-support-containers-that-require-gpus
https://hpc.nih.gov/apps/singularity.html#gpu

**Comment by HannoSpreeuw** [comment]
The new `containers` branch can e.g. build `sagecal_gpu` from the `dev` branch on a Singularity container with Ubuntu Bionic.

I erroneously branched `containers` off `master` instead of `dev`.
Please let me know if I should restore that.

**Comment by SarodYatawatta** [comment]
I think dev should be used, not master

**Comment by HannoSpreeuw** [comment]
But if I can merge `containers` with `dev`, it should still be okay.

**Comment by SarodYatawatta** [comment]
yes

**Comment by HannoSpreeuw** [comment]
I will try [rebase](https://stackoverflow.com/questions/21805925/accidentally-branched-off-of-the-wrong-branch-and-when-i-want-to-merge-into-the) first.

**Comment by HannoSpreeuw** [comment]
`git rebase --onto dev master containers`
leads to
`fatal: Does not point to a valid commit 'dev'`

**Comment by HannoSpreeuw** [comment]
I could still submit a PR for merging into `dev`.
But that can't automatically merge.

**Comment by HannoSpreeuw** [comment]
I tried a different approach.
`git stash` in the `containers` branch.
`git checkout dev`
`git stash pop`.
"Auto-merging Docker/ubuntu1604-test/Dockerfile
CONFLICT (content): Merge conflict in Docker/ubuntu1604-test/Dockerfile"

So I had forgotten about a minor change in `Docker/ubuntu1604-test/Dockerfile` in the `containers` branch. Irrelevant to the changes I wanted to push. Big mistake and git is very unforegiving.

So I tried to overwrite this file with the remote file:
`git fetch`
`git checkout origin/dev ../../Docker/ubuntu1604-test/Dockerfile`
But that does not help:
```git stash pop
Auto-merging Docker/ubuntu1604-test/Dockerfile
CONFLICT (content): Merge conflict in Docker/ubuntu1604-test/Dockerfile```

Seems I am completely stuck.
I also tried 
`git mergetool --tool=vimdiff`
to make ../../Docker/ubuntu1604-test/Dockerfile exactly the same as remote.
`git add ../../Docker/ubuntu1604-test/Dockerfile`
`git commit -m "Local file the same as remote"`
`git push`

But the merge problem persists. 

Such I stupid thing. Just two files that I would like to add to the `dev` branch, should be so simple.

**Comment by HannoSpreeuw** [comment]
This was completed.
From the Singularity definition file in [the Singularity folder](https://github.com/nlesc-dirac/sagecal/tree/dev/Singularity/ubuntu1804-test) one can easily build a Singularity image.
From a container instantiated from this image I have deployed sagecal on a GPU.
